# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Enable Unprivileged Ping
      run: |
        sudo sysctl -w "$(printf 'net.ipv4.ping_group_range=0\t10000')"

      # While IPv4 loopback has a netmask of /24, the IPv6 loopback has a single
      # address in it. This expands it to have more addresses, which ensures
      # there are some nonfunctional IPv6 addresses (e.g. ::2) in the routing table.
    - name: Expand loopback network
      run: |
        sudo ifconfig lo inet6 del ::1 add ::1/126

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
