# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        race: ["", "-race"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Enable Unprivileged Ping
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo sysctl -w "$(printf 'net.ipv4.ping_group_range=0\t10000')"

        # While IPv4 loopback has a netmask of /24, the IPv6 loopback has a single
        # address in it. This expands it to have more addresses, which ensures
        # there are some nonfunctional IPv6 addresses (e.g. ::2) in the routing table.
      - name: Expand loopback network
        run: |
          case "$RUNNER_OS" in
            Linux)
              sudo ifconfig lo inet6 del ::1 add ::1/126
              ;;
            macOS)
              sudo ifconfig lo0 inet6 delete ::1
              sudo ifconfig lo0 inet6 add ::1 prefixlen 126
              ;;
            *)
              echo "Unsupported OS: $RUNNER_OS" >&2
              exit 1
              ;;
          esac

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build ${{ matrix.race }} -v ./...

      - name: Test
        run: go test ${{ matrix.race }} -v ./...
